### ISSUE TITLE
Continous Delivery Platform

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/core_repo#9]
A CD platform should be set up.

**Comment by mehmetcelikel** [comment]
* Jenkins is installed to server. (http://46.101.225.73:8080)
* A jenkins job is created in order to trigger build process (checkout + compile + deploy). (http://46.101.225.73:8080/job/SWE574-master-build/)
* A webhook is created on Github in order to convey push events to jenkins server. (https://github.com/swe574-2015fall-group2/core_repo/settings/hooks)
* I wrote followin shell scripts in order to checkout, compile and deploy application.
  - checkoutAndBuild.sh
  - killApplication.sh
  - run.sh
